version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    environment:
      RAILS_ENV: development
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_PORT: 5432
      OTEL_TRACES_EXPORTER: otlp
      # Set these as needed or pass with `--env-file` or `-e`
      OTEL_EXPORTER_OTLP_ENDPOINT: "https://otel.observability.app.launchdarkly.com:4318"
      OTEL_RESOURCE_ATTRIBUTES: "highlight.project_id=YOUR_LD_SDK_KEY"
      REDIS_URL: "redis://redis:6379/0"
      # Datadog configuration
      DD_AGENT_HOST: datadog
      DD_TRACE_AGENT_PORT: 8126
      DD_ENV: dev
      DD_SERVICE: rails-otel-example
      DD_VERSION: 1.0.0
    volumes:
      - .:/workspaces/rails-otel-example:cached
    ports:
      - "3000:3000"
    command: bash -lc "bundle config set without 'production' && bundle install && bundle exec rails db:prepare && bundle exec rails server -b 0.0.0.0 -p 3000"
    depends_on:
      - db
      - redis
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
  datadog:
    image: gcr.io/datadoghq/agent:7
    environment:
      DD_API_KEY: "2a22be7fedee3e848ba416265cf0d6a9"
      DD_SITE: "us5.datadoghq.com"
      DD_ENV: "dev"
      DD_DOGSTATSD_NON_LOCAL_TRAFFIC: "true"
      DD_APM_ENABLED: "true"
      DD_APM_NON_LOCAL_TRAFFIC: "true"
      DD_LOGS_ENABLED: "true"
      DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL: "true"
      DD_CONTAINER_EXCLUDE: "name:datadog-agent"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    ports:
      - "8125:8125/udp"  # DogStatsD
      - "8126:8126"      # APM traces
volumes:
  pgdata:
  redisdata:


